spring.application.name=calculei
server.port = ${PORT}
swagger_host = ${SWHOST}
spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.default_schema=calcjud
spring.datasource.platform=postgres
spring.datasource.url=${OPENSHIFT_DB}
spring.datasource.username=${dbusername}
spring.datasource.password=${dbpassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.jpa.hibernate.ddl-auto=update

