name: Continuous Integration, Delivery and Deployment With GitHub Actions

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  # ---------------------------------------------------
  # 1. BUILD
  # ---------------------------------------------------
  build:
    name: Build the Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-padrao

      - name: Build Application .jar
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculei-app
          path: target/*.jar

  # ---------------------------------------------------
  # 2. TESTES
  # ---------------------------------------------------
  test:
    name: Test the Application
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: calculei_test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Padrão
        uses: ./.github/actions/setup-padrao

      - name: Test Application
        env:
          PORT: 8080
          DB_HOST: localhost
          DB_NAME: calculei_test_db
          DB_USER: test_user
          DB_PASSWORD: test_password
          MAIL_HOST: localhost
          MAIL_PORT: 1025
          MAIL_USERNAME: dev
          MAIL_PASSWORD: dev

        run: mvn test

  # ---------------------------------------------------
  # 3. Security Scan
  # ---------------------------------------------------
  security-scan:
    name: Security Scan the Application
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: ./.github/actions/setup-padrao

      - name: Credential Scan (TruffleHog)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --only-verified

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Dependency Vulnerability Scan (Snyk)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run:
          chmod +x mvnw || true
          snyk test --all-projects --severity-threshold=high
          snyk monitor --all-projects

  # ---------------------------------------------------
  # 4. Quality Scan
  # ---------------------------------------------------
  quality-scan:
    name: Verify Code Quality with qodana
    needs: security-scan
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-padrao

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2026.1
        with:
          args: --fail-threshold=1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  # ---------------------------------------------------
  # 5. Continuous Delivery in AWS
  # ---------------------------------------------------
  continuous-delivery:
    name: Continuous Delivery in AWS
    needs: quality-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-padrao

      - name: Set up QEMU (Para suportar builds ARM64)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: calculei-app
          path: target/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          build-args: |
            APP_VERSION=${{ github.run_id }}
          tags: |
            ${{ secrets.IMAGE_REPO_URL }}:latest
            ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}

  # ---------------------------------------------------
  # 6. Continuous Deployment in AWS
  # ---------------------------------------------------
  continuous-deployment:
    name: Continuous Deployment in AWS
    needs: continuous-delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-padrao

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ secrets.SERVICE_NAME }}
          cluster: ${{ secrets.CLUSTER_NAME }}
          wait-for-service-stability: true